/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositReward"
      | "reclaimUnusedFunds"
      | "releaseReward"
      | "setSettlement"
      | "settlementContract"
      | "taskBalances"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsReclaimed"
      | "RewardDeposited"
      | "RewardReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositReward",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimUnusedFunds",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReward",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlement",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskBalances",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclaimUnusedFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskBalances",
    data: BytesLike
  ): Result;
}

export namespace FundsReclaimedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    sponsor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, sponsor: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    sponsor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDepositedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    sponsor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, sponsor: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    sponsor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowVault;
  waitForDeployment(): Promise<this>;

  interface: EscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositReward: TypedContractMethod<[taskId: BytesLike], [void], "payable">;

  reclaimUnusedFunds: TypedContractMethod<
    [taskId: BytesLike, sponsor: AddressLike],
    [void],
    "nonpayable"
  >;

  releaseReward: TypedContractMethod<
    [taskId: BytesLike, participant: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSettlement: TypedContractMethod<
    [_settlement: AddressLike],
    [void],
    "nonpayable"
  >;

  settlementContract: TypedContractMethod<[], [string], "view">;

  taskBalances: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositReward"
  ): TypedContractMethod<[taskId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "reclaimUnusedFunds"
  ): TypedContractMethod<
    [taskId: BytesLike, sponsor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseReward"
  ): TypedContractMethod<
    [taskId: BytesLike, participant: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlement"
  ): TypedContractMethod<[_settlement: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "taskBalances"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "FundsReclaimed"
  ): TypedContractEvent<
    FundsReclaimedEvent.InputTuple,
    FundsReclaimedEvent.OutputTuple,
    FundsReclaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDeposited"
  ): TypedContractEvent<
    RewardDepositedEvent.InputTuple,
    RewardDepositedEvent.OutputTuple,
    RewardDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReleased"
  ): TypedContractEvent<
    RewardReleasedEvent.InputTuple,
    RewardReleasedEvent.OutputTuple,
    RewardReleasedEvent.OutputObject
  >;

  filters: {
    "FundsReclaimed(bytes32,address,uint256)": TypedContractEvent<
      FundsReclaimedEvent.InputTuple,
      FundsReclaimedEvent.OutputTuple,
      FundsReclaimedEvent.OutputObject
    >;
    FundsReclaimed: TypedContractEvent<
      FundsReclaimedEvent.InputTuple,
      FundsReclaimedEvent.OutputTuple,
      FundsReclaimedEvent.OutputObject
    >;

    "RewardDeposited(bytes32,address,uint256)": TypedContractEvent<
      RewardDepositedEvent.InputTuple,
      RewardDepositedEvent.OutputTuple,
      RewardDepositedEvent.OutputObject
    >;
    RewardDeposited: TypedContractEvent<
      RewardDepositedEvent.InputTuple,
      RewardDepositedEvent.OutputTuple,
      RewardDepositedEvent.OutputObject
    >;

    "RewardReleased(bytes32,address,uint256)": TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;
    RewardReleased: TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;
  };
}
