/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "escrowVault"
      | "markRejectedOnly"
      | "markVerifiedOnly"
      | "recordSubmission"
      | "releaseReward"
      | "resolveAndSettle"
      | "settled"
      | "submissionRegistry"
      | "taskRegistry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Settled"): EventFragment;

  encodeFunctionData(
    functionFragment: "escrowVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markRejectedOnly",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markVerifiedOnly",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubmission",
    values: [BytesLike, BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReward",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveAndSettle",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settled",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "escrowVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markRejectedOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markVerifiedOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveAndSettle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submissionRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskRegistry",
    data: BytesLike
  ): Result;
}

export namespace SettledEvent {
  export type InputTuple = [
    taskId: BytesLike,
    submissionId: BytesLike,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    submissionId: string,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    submissionId: string;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Settlement extends BaseContract {
  connect(runner?: ContractRunner | null): Settlement;
  waitForDeployment(): Promise<this>;

  interface: SettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  escrowVault: TypedContractMethod<[], [string], "view">;

  markRejectedOnly: TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  markVerifiedOnly: TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordSubmission: TypedContractMethod<
    [
      submissionId: BytesLike,
      taskId: BytesLike,
      participant: AddressLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  releaseReward: TypedContractMethod<
    [taskId: BytesLike, submissionId: BytesLike],
    [void],
    "nonpayable"
  >;

  resolveAndSettle: TypedContractMethod<
    [
      taskId: BytesLike,
      submissionId: BytesLike,
      score: BigNumberish,
      thresholdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settled: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  submissionRegistry: TypedContractMethod<[], [string], "view">;

  taskRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "escrowVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markRejectedOnly"
  ): TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markVerifiedOnly"
  ): TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordSubmission"
  ): TypedContractMethod<
    [
      submissionId: BytesLike,
      taskId: BytesLike,
      participant: AddressLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseReward"
  ): TypedContractMethod<
    [taskId: BytesLike, submissionId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveAndSettle"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      submissionId: BytesLike,
      score: BigNumberish,
      thresholdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settled"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submissionRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "taskRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Settled"
  ): TypedContractEvent<
    SettledEvent.InputTuple,
    SettledEvent.OutputTuple,
    SettledEvent.OutputObject
  >;

  filters: {
    "Settled(bytes32,bytes32,address,uint256)": TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
    Settled: TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
  };
}
