/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SubmissionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSubmission"
      | "markPaid"
      | "markRejected"
      | "markVerified"
      | "recordSubmission"
      | "setSettlement"
      | "settlementContract"
      | "submissions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RewardReleased"
      | "SubmissionRecorded"
      | "SubmissionRejected"
      | "SubmissionVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "markPaid", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "markRejected",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markVerified",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubmission",
    values: [BytesLike, BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlement",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
}

export namespace RewardReleasedEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: string,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    submissionId: string;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionRecordedEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    taskId: BytesLike,
    participant: AddressLike,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    submissionId: string,
    taskId: string,
    participant: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    submissionId: string;
    taskId: string;
    participant: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionRejectedEvent {
  export type InputTuple = [submissionId: BytesLike, score: BigNumberish];
  export type OutputTuple = [submissionId: string, score: bigint];
  export interface OutputObject {
    submissionId: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionVerifiedEvent {
  export type InputTuple = [submissionId: BytesLike, score: BigNumberish];
  export type OutputTuple = [submissionId: string, score: bigint];
  export interface OutputObject {
    submissionId: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubmissionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SubmissionRegistry;
  waitForDeployment(): Promise<this>;

  interface: SubmissionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSubmission: TypedContractMethod<
    [submissionId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        participant: string;
        status: bigint;
        score: bigint;
        payoutDone: boolean;
      }
    ],
    "view"
  >;

  markPaid: TypedContractMethod<
    [submissionId: BytesLike],
    [void],
    "nonpayable"
  >;

  markRejected: TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  markVerified: TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordSubmission: TypedContractMethod<
    [
      submissionId: BytesLike,
      taskId: BytesLike,
      participant: AddressLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setSettlement: TypedContractMethod<
    [_settlement: AddressLike],
    [void],
    "nonpayable"
  >;

  settlementContract: TypedContractMethod<[], [string], "view">;

  submissions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        participant: string;
        evidenceHash: string;
        status: bigint;
        score: bigint;
        payoutDone: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [submissionId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        participant: string;
        status: bigint;
        score: bigint;
        payoutDone: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markPaid"
  ): TypedContractMethod<[submissionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markRejected"
  ): TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markVerified"
  ): TypedContractMethod<
    [submissionId: BytesLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordSubmission"
  ): TypedContractMethod<
    [
      submissionId: BytesLike,
      taskId: BytesLike,
      participant: AddressLike,
      evidenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlement"
  ): TypedContractMethod<[_settlement: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean] & {
        participant: string;
        evidenceHash: string;
        status: bigint;
        score: bigint;
        payoutDone: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RewardReleased"
  ): TypedContractEvent<
    RewardReleasedEvent.InputTuple,
    RewardReleasedEvent.OutputTuple,
    RewardReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionRecorded"
  ): TypedContractEvent<
    SubmissionRecordedEvent.InputTuple,
    SubmissionRecordedEvent.OutputTuple,
    SubmissionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionRejected"
  ): TypedContractEvent<
    SubmissionRejectedEvent.InputTuple,
    SubmissionRejectedEvent.OutputTuple,
    SubmissionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionVerified"
  ): TypedContractEvent<
    SubmissionVerifiedEvent.InputTuple,
    SubmissionVerifiedEvent.OutputTuple,
    SubmissionVerifiedEvent.OutputObject
  >;

  filters: {
    "RewardReleased(bytes32,address,uint256)": TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;
    RewardReleased: TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;

    "SubmissionRecorded(bytes32,bytes32,address,bytes32)": TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;
    SubmissionRecorded: TypedContractEvent<
      SubmissionRecordedEvent.InputTuple,
      SubmissionRecordedEvent.OutputTuple,
      SubmissionRecordedEvent.OutputObject
    >;

    "SubmissionRejected(bytes32,uint256)": TypedContractEvent<
      SubmissionRejectedEvent.InputTuple,
      SubmissionRejectedEvent.OutputTuple,
      SubmissionRejectedEvent.OutputObject
    >;
    SubmissionRejected: TypedContractEvent<
      SubmissionRejectedEvent.InputTuple,
      SubmissionRejectedEvent.OutputTuple,
      SubmissionRejectedEvent.OutputObject
    >;

    "SubmissionVerified(bytes32,uint256)": TypedContractEvent<
      SubmissionVerifiedEvent.InputTuple,
      SubmissionVerifiedEvent.OutputTuple,
      SubmissionVerifiedEvent.OutputObject
    >;
    SubmissionVerified: TypedContractEvent<
      SubmissionVerifiedEvent.InputTuple,
      SubmissionVerifiedEvent.OutputTuple,
      SubmissionVerifiedEvent.OutputObject
    >;
  };
}
