/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TaskRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "closeTask" | "createTask" | "getTask" | "tasks"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TaskClosed" | "TaskCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "closeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "closeTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
}

export namespace TaskClosedEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    sponsor: AddressLike,
    rewardAmount: BigNumberish,
    thresholdBps: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: string,
    sponsor: string,
    rewardAmount: bigint,
    thresholdBps: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    taskId: string;
    sponsor: string;
    rewardAmount: bigint;
    thresholdBps: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TaskRegistry;
  waitForDeployment(): Promise<this>;

  interface: TaskRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  createTask: TypedContractMethod<
    [
      taskId: BytesLike,
      rewardAmount: BigNumberish,
      thresholdBps: BigNumberish,
      metadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        sponsor: string;
        rewardAmount: bigint;
        thresholdBps: bigint;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        sponsor: string;
        rewardAmount: bigint;
        thresholdBps: bigint;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      rewardAmount: BigNumberish,
      thresholdBps: BigNumberish,
      metadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        sponsor: string;
        rewardAmount: bigint;
        thresholdBps: bigint;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string, boolean] & {
        sponsor: string;
        rewardAmount: bigint;
        thresholdBps: bigint;
        metadataHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TaskClosed"
  ): TypedContractEvent<
    TaskClosedEvent.InputTuple,
    TaskClosedEvent.OutputTuple,
    TaskClosedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "TaskClosed(bytes32)": TypedContractEvent<
      TaskClosedEvent.InputTuple,
      TaskClosedEvent.OutputTuple,
      TaskClosedEvent.OutputObject
    >;
    TaskClosed: TypedContractEvent<
      TaskClosedEvent.InputTuple,
      TaskClosedEvent.OutputTuple,
      TaskClosedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,uint256,uint256,bytes32)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
